@asdc2024.weather_HostAddress = http://localhost:5255
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJzdHJpbmciLCJnaXZlbl9uYW1lIjoiVGhvcnN0ZW4iLCJmYW1pbHlfbmFtZSI6IkthbnN5IiwiZW1haWwiOiJ0a2Fuc3lAZG90bmV0Y29uc3VsdGluZy5ldSIsImh0dHA6Ly9zY2hlbWFzLmRvdG5ldGNvbnN1bHRpbmcuZXUvd3MvMjAyNC8wNS9pZGVudGl0eS9jbGFpbXMvY3VsdHVyZSI6ImRlLURFIiwicm9sZSI6WyJBZG1pbiIsIlVzZXIiLCJTdXBlclVzZXIiXSwibmJmIjoxNzE1MDA2ODIzLCJleHAiOjE3MTUwOTMyMjMsImlhdCI6MTcxNTAwNjgyMywiaXNzIjoiS2Fuc3kgQUcifQ.z1hoGc9r4UQ1P_FFKuL8eOPhQ9A5d3e2oXzTSzs7Euk

### Testaufruf
GET {{asdc2024.weather_HostAddress}}/weatherforecast
Authorization: Bearer {{jwt}}

###
